# This file injects SIMD options for Embree
set(EMBREE_ISA_SSE2 OFF CACHE BOOL "")
set(EMBREE_ISA_SSE42 OFF CACHE BOOL "")
set(EMBREE_ISA_AVX ON CACHE BOOL "")
set(EMBREE_ISA_AVX2 OFF CACHE BOOL "")
set(EMBREE_ISA_AVX512 OFF CACHE BOOL "")
