# SPDX-FileCopyrightText: 2025 Howetuft
#
#
# SPDX-License-Identifier: Apache-2.0


# Check that dependencies are buildable


name: LuxCore Dependency Checker

permissions: read-all

on:
  workflow_dispatch:
  push:

jobs:
  call-build-deps:
    uses: ./.github/workflows/build.yml
    with:
      # This must be kept in lower case (incorporated to Conan package name)
      luxdeps-version: "check"
