# SPDX-FileCopyrightText: 2025 Howetuft
#
#
# SPDX-License-Identifier: Apache-2.0


# Monitor buildability.
#
# This workflow periodically triggers a build of LuxCoreDeps to ensure it stays
# buildable. The build is typically launched on a daily basis.


name: LuxCore Dependency Monitoring

permissions: read-all

on:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  call-build-deps:
    uses: ./.github/workflows/build.yml
    with:
      # This must be kept in lower case (incorporated to Conan package name)
      luxdeps-version: "monitor"
